export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const USER_ACCOUNT = "USER_ACCOUNT";
export const COMPANY_CREATE = "COMPANY_CREATE";
export const COMPANY_STARTCREATING = "COMPANY_STARTCREATING";
export const JOB_DETAILS = "JOB_DETAILS";
